version: '3.9'

services:
  http_server:
    build:
      context: .
      dockerfile: ./http_server/Dockerfile
    container_name: http_server
    working_dir: /app
    ports:
    - "1323:1323"
    networks:
    - telego_network
    volumes:
    - ./http_server/:/app
    env_file:
    - ./http_server/.env
    depends_on:
        - arangodb
  arangodb:
    image: arangodb
    ports:
      - "8529:8529"
    networks:
    - telego_network

networks:
  telego_network:
    name: telego_network
    driver: bridge
    
#volumes:
# add db volume  
