version: '3.9'

services:
  http_server:
    build:
      context: .
      dockerfile: ./http_server/Dockerfile
    container_name: http_server
    working_dir: /app
    ports:
    - "1323:1323"
    networks:
    - telego_network
    volumes:
    - ./http_server/:/app
    env_file:
    - ./http_server/.env
    depends_on:
        - neo4j
  neo4j:
    image: neo4j
    networks:
    - telego_network
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - neo.env
    volumes:
      - $HOME/neo4j/data:/data
  # cassandra: 
  #   image: cassandra
  # elasticsearch:
  #   image: elasticsearch:8.5.3

networks:
  telego_network:
    name: telego_network
    driver: bridge
    
#volumes:
# add db volume  
